language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.7-dev'
install:
- pip install -r requirements.txt
script:
  - echo "Here I must put some tests"
deploy:
  provider: pypi
  user: andreacioni
  password:
    secure: "Zcr2K75YsVpxf/c3d1DDFbW2ecsEuC+ANAeMr0jnACVt8JPJdUY93Jn2QsCXJVnjnXx31BjAc21B/ewncrJY5201ZPTxS6q6+Xa+N6pgKQUoSarakDPOrkg9pz3CEpt8Xrnw7c5VqJ34IHpKf+poH/AMrNI7QDYbGpGgnu83CdKczL2F11yYJqXSF1mbdRg2jwdgLYmrIq8OQAZe5SINb8OcxA6478tzzK/uJKle3jazzgBqMpBLp3rf7oouNLYerFKYhi57p9nYc5PKlHJIiDS3q9nXTO0fWXiGvIXQo3x5EEpfHwi185ly4JPi8zetlfNJXXXkm6kBCTrYnwcDIxlbf9TxY60vXQh4k6y2wbDOGHBCF5bMuKLa4AMMcMqF2qWh66Q98SEftuEOqra4bnyKeJHECCb223z7g8ZqVjNFHi2evOf/Rkf3xF7qK0QLFjTOrv2+v80TD04n3rHfSIMovpjN9s8+9IDPwxvg+GdrkleeeE737j1CCRsgfsrf7IIy2jx/ut5+HtwBdeSlP1jkhGcYlhgiBahWIyS7udFaasFeQ5G61b09l03adjm12w7i5x5loTfdrXt6bhGcanE8g0Ql2l8/GDu76byPaEDvax6L+89eMsKC11DygzNQ2VfaNhz1A6i1a3hr52Gbj1ROQA3upcTO6Epz9jtm7a8="
  skip_cleanup: true
  on:
    tags: true
